// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: mental_wellness.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInput) Reset() {
	*x = UserInput{}
	mi := &file_mental_wellness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInput) ProtoMessage() {}

func (x *UserInput) ProtoReflect() protoreflect.Message {
	mi := &file_mental_wellness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInput.ProtoReflect.Descriptor instead.
func (*UserInput) Descriptor() ([]byte, []int) {
	return file_mental_wellness_proto_rawDescGZIP(), []int{0}
}

func (x *UserInput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotResponse) Reset() {
	*x = BotResponse{}
	mi := &file_mental_wellness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotResponse) ProtoMessage() {}

func (x *BotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mental_wellness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotResponse.ProtoReflect.Descriptor instead.
func (*BotResponse) Descriptor() ([]byte, []int) {
	return file_mental_wellness_proto_rawDescGZIP(), []int{1}
}

func (x *BotResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_mental_wellness_proto protoreflect.FileDescriptor

const file_mental_wellness_proto_rawDesc = "" +
	"\n" +
	"\x15mental_wellness.proto\x12\x13mental_wellness_bot\"%\n" +
	"\tUserInput\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"#\n" +
	"\vBotResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply2i\n" +
	"\x11MentalWellnessBot\x12T\n" +
	"\x10GenerateResponse\x12\x1e.mental_wellness_bot.UserInput\x1a .mental_wellness_bot.BotResponseB:Z8github.com/ramyasreetejo/mental_wellness_bot/proto;protob\x06proto3"

var (
	file_mental_wellness_proto_rawDescOnce sync.Once
	file_mental_wellness_proto_rawDescData []byte
)

func file_mental_wellness_proto_rawDescGZIP() []byte {
	file_mental_wellness_proto_rawDescOnce.Do(func() {
		file_mental_wellness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mental_wellness_proto_rawDesc), len(file_mental_wellness_proto_rawDesc)))
	})
	return file_mental_wellness_proto_rawDescData
}

var file_mental_wellness_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mental_wellness_proto_goTypes = []any{
	(*UserInput)(nil),   // 0: mental_wellness_bot.UserInput
	(*BotResponse)(nil), // 1: mental_wellness_bot.BotResponse
}
var file_mental_wellness_proto_depIdxs = []int32{
	0, // 0: mental_wellness_bot.MentalWellnessBot.GenerateResponse:input_type -> mental_wellness_bot.UserInput
	1, // 1: mental_wellness_bot.MentalWellnessBot.GenerateResponse:output_type -> mental_wellness_bot.BotResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mental_wellness_proto_init() }
func file_mental_wellness_proto_init() {
	if File_mental_wellness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mental_wellness_proto_rawDesc), len(file_mental_wellness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mental_wellness_proto_goTypes,
		DependencyIndexes: file_mental_wellness_proto_depIdxs,
		MessageInfos:      file_mental_wellness_proto_msgTypes,
	}.Build()
	File_mental_wellness_proto = out.File
	file_mental_wellness_proto_goTypes = nil
	file_mental_wellness_proto_depIdxs = nil
}
